services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nvidia-ui-backend
    environment:
      - DATABASE_URL=sqlite:////data/scaleup_nvidia.db
      - ALLOWED_ORIGINS=http://localhost:3000
      - SECRET_KEY=dev-secret
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    volumes:
      - backend_data:/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nvidia-ui-frontend
    environment:
      - PORT=3000
      - NODE_ENV=production
      - BACKEND_API_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
    driver: local
