services:
  postgres:
    image: postgres:15
    container_name: nvidia-ui-postgres
    environment:
      - POSTGRES_DB=scaleup_nvidia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nvidia-ui-backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/scaleup_nvidia
      - ALLOWED_ORIGINS=http://localhost:3000
      - SECRET_KEY=dev-secret
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - REGISTRY_BASE_URL=http://host.docker.internal:7000
      - PUBLIC_BASE_URL=http://localhost:8000
      - SERVICE_ID=nvidia-ui-backend
      - REGISTRY_RETRY_ATTEMPTS=3
      - REGISTRY_RETRY_DELAY=1
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nvidia-ui-frontend
    environment:
      - PORT=3000
      - NODE_ENV=production
      - BACKEND_API_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
